/** @type {import('jest').Config} */
const COVERAGE_FILES = [
  'src/config.ts',
  'src/context.ts',
  'src/global.ts',
  'src/history-fix.ts',
  'src/hocs.ts',
  'src/keep-alive.ts',
  'src/match-path.ts',
  'src/navigation-signal.ts',
  'src/route-guard.ts',
  'src/route-hydration-server.ts',
  'src/route-lazy.ts',
  'src/route-lazy-renderer.ts',
  'src/route-runtime.ts',
  'src/route-runtime-navigation.ts',
  'src/route-runtime-context.ts',
  'src/standalone-route-ssr-adapter.ts',
  'src/standalone-modern.ts',
  'src/standalone-legacy.ts',
  'src/router-link.ts',
  'src/router-view.ts',
  'src/router.ts',
  'src/util.ts',
  'src/view-position.ts',
  'src/history/browser.ts',
  'src/history/hash.ts',
  'src/history/history.ts',
  'src/history/memory.ts',
  'src/history/utils.ts',
  'src/hooks/base.ts',
  'src/hooks/use-manual-router.ts',
  'src/hooks/use-route-title.ts',
  'drawer/src/drawer.ts',
  'drawer/src/RouterDrawer.ts',
  'drawer/src/context.ts',
  'drawer/src/presenter.ts',
  'transition/src/CSSTransition.ts',
  'transition/src/RouterView.ts',
  'transition/src/SwitchTransition.ts',
  'transition/src/Transition.ts',
  'transition/src/TransitionPresenter.ts',
  'transition/src/TransitionPresenterContext.ts',
  'transition/src/TransitionViewPresenter.ts',
];

module.exports = {
  testEnvironment: 'jsdom',
  coverageProvider: 'babel',
  coverageReporters: ['text', 'json', 'json-summary', 'lcov'],
  roots: ['<rootDir>/__tests__'],
  testMatch: ['**/__tests__/**/*.test.(ts|tsx|js)'],
  transform: {
    '^.+\\.(ts|tsx|js|jsx)$': 'babel-jest',
  },
  transformIgnorePatterns: [
    '/node_modules/(?!react-transition-group/)',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  moduleNameMapper: {
    '^react-view-router/dom$': '<rootDir>/dom/src/index.ts',
    '^react-view-router/transition$': '<rootDir>/transition/src/index.ts',
    '^react-view-router/drawer$': '<rootDir>/drawer/src/index.ts',
    '^react-view-router$': '<rootDir>/src/index.ts',
    '^\\.\\./\\.\\.$': '<rootDir>/src/index.ts',
    '\\.(css|scss)(\\?.*)?$': '<rootDir>/__tests__/helpers/style-mock.js',
    '\\.(png|jpe?g|gif|webp|svg)(\\?.*)?$': '<rootDir>/__tests__/helpers/file-mock.js',
  },
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    'dom/src/**/*.{ts,tsx}',
    'drawer/src/**/*.{ts,tsx}',
    'transition/src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!dom/src/**/*.d.ts',
    '!drawer/src/**/*.d.ts',
    '!transition/src/**/*.d.ts',
    '!src/types/**',
    '!src/**/index.ts',
    '!dom/src/index.ts',
    '!drawer/src/index.ts',
    '!transition/src/index.ts',
    '!src/history/types.ts',
    '!src/keep-alive-dom.tsx',
    '!src/router-coverage-helpers.ts',
  ],
  coverageThreshold: {
    global: {
      lines: 95,
      functions: 80,
      statements: 95,
      branches: 95,
    },
    ...Object.fromEntries(
      COVERAGE_FILES.map((file) => [file, { statements: 95, branches: 95, lines: 95 }]),
    ),
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  modulePathIgnorePatterns: ['<rootDir>/esm', '<rootDir>/es', '<rootDir>/demo'],
};
